### ISSUE TITLE
[Suggestion] Add need enable Docker integration for WSL in the installation guild

### ISSUE THREAD

**Issue by whats2000** [microsoft/vscode-tree-sitter-wasm#17]
#### Description
Building WebAssembly (WASM) using this repository on Windows Subsystem for Linux (WSL2) requires Docker integration to be enabled. If Docker integration for WSL is not enabled, the build process results in an error. This requirement is not currently documented in the installation guide.

#### Steps to Reproduce
1. Set up the repository in WSL on a Windows machine without enabling Docker integration for WSL.
2. Attempt to build WASM according to the provided instructions.

#### Expected Behavior
The build process should succeed if prerequisites are met or documentation should clearly state all requirements.

#### Actual Behavior
The build fails with a process error if Docker integration for WSL is not enabled.

#### Suggested Solution
Update the installation guide to include the following note:
> **Note**: Ensure Docker integration for WSL is enabled before attempting to build WASM. Without this integration, the build process may encounter errors.

#### Additional Information
- **Environment**: WSL2 on Windows Ubuntu 22.04

**Comment by alexr00** [comment]
Adding with https://github.com/microsoft/vscode-tree-sitter-wasm/pull/18.
